name: Bragi
favicon: null
layout_spectrum: 0.07377268793061376
typography_spectrum: 0.9398302235640585
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3392941039055586
  lightness: 0.9104100619442761
  saturation: 0.8409306025132537
  rhythmicContrast: 0.5151679078117013
purpose: []
